services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blog-network
    ports:
      - '5432:5432'

networks:
  blog-network:
    driver: bridge

volumes:
  postgres-data:
